name: VPS Session
on:
  schedule:
    - cron: '0 */6 * * *'  # Каждые 6 часов
  workflow_dispatch:       # Возможность запуска вручную

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350   # Чуть меньше 6 часов
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y tmate curl unzip sudo net-tools neofetch

      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh

      - name: Start Tailscale
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=vps-github

      - name: Start tmate session for SSH access
        uses: mxschmitt/action-tmate@v3

      - name: Show Tailscale IP and tmate info
        run: |
          echo "Tailscale IP:"
          tailscale ip -4
