name: VPS Session
on:
  workflow_dispatch:

jobs:
  vps-session:
    runs-on: ubuntu-latest
    timeout-minutes: 350
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Install prerequisites
        run: |
          sudo apt update
          sudo apt install -y curl unzip sudo net-tools
      - name: Install Tailscale
        run: |
          curl -fsSL https://tailscale.com/install.sh | sh
      - name: Start Tailscale with SSH
        run: |
          sudo tailscaled &
          sleep 8
          sudo tailscale up --authkey ${{ secrets.TAILSCALE_AUTHKEY }} --hostname=vps-github --ssh
      - name: Show Tailscale IP
        run: |
          echo "Ваш Tailscale IP-адрес:"
          tailscale ip -4
      - name: Keep session alive for 6 hours
        run: sleep 21600
